name: Versionado automático con Commitizen

on:
  push:
    branches:
      - master  # o main, según tu repo

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # necesario para tags

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Instalar Commitizen
      run: pip install commitizen

    - name: Ejecutar bump y crear tag
      run: |
        cz bump --yes

    - name: Push cambios y tags
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git push origin HEAD:master --tags
