// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLpBnvpkrpZ1gF1i7tvVQ9G4B0cNVbh38',
    appId: '1:633840814710:web:d614c3491de282973f2d57',
    messagingSenderId: '633840814710',
    projectId: 'lab-cg',
    authDomain: 'lab-cg.firebaseapp.com',
    storageBucket: 'lab-cg.firebasestorage.app',
    measurementId: 'G-YP10EY9CFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIqY0Mk7aovlxUPjsrCFsmyeVGaSho2iI',
    appId: '1:633840814710:android:ae983cf91e0caacb3f2d57',
    messagingSenderId: '633840814710',
    projectId: 'lab-cg',
    storageBucket: 'lab-cg.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD47jO3nsyn4FcI6Atuu78z5nhgkDVNeTA',
    appId: '1:633840814710:ios:f642515e9b38e7623f2d57',
    messagingSenderId: '633840814710',
    projectId: 'lab-cg',
    storageBucket: 'lab-cg.firebasestorage.app',
    iosBundleId: 'com.example.labCg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD47jO3nsyn4FcI6Atuu78z5nhgkDVNeTA',
    appId: '1:633840814710:ios:f642515e9b38e7623f2d57',
    messagingSenderId: '633840814710',
    projectId: 'lab-cg',
    storageBucket: 'lab-cg.firebasestorage.app',
    iosBundleId: 'com.example.labCg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLpBnvpkrpZ1gF1i7tvVQ9G4B0cNVbh38',
    appId: '1:633840814710:web:39bb4d3d12b849b73f2d57',
    messagingSenderId: '633840814710',
    projectId: 'lab-cg',
    authDomain: 'lab-cg.firebaseapp.com',
    storageBucket: 'lab-cg.firebasestorage.app',
    measurementId: 'G-7HE0MLP0JD',
  );
}
